ClassNoteArchive/urls.py
from django.contrib import admin
from django.urls import path

# here....

urlpatterns = [
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.homepage, name='homepage'), 
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

app_name = 'users'

urlpatterns = [
    path('user/login/', views.loginUser, name='loginUser'),
    path('user/register/', views.registerUser, name='registerUser'), 
    path('', include(('posts.urls', 'posts'), namespace='posts')), 
]

posts/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=100, primary_key=True)
    description = models.CharField(max_length=500, blank=True)
    def __str__(self):
        return self.tag_name

class Post(models.Model):
    title = models.CharField(max_length=500)
    created_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True)
    description = models.TextField(blank=True)
    link = models.CharField(max_length=500, blank=True)
    tags = models.ManyToManyField(Tag)
    total_upvote = models.IntegerField(default=0)
    total_downvote = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class University(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=500, blank=True)
    def __str__(self): 
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.SET_NULL, null=True, blank=True)
    user_type_choices = [('User', 'User'), ('Privileged User', 'Privileged User')]
    user_type = models.CharField(choices=user_type_choices, max_length=20, default='User')
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    admission_year = models.DateField(blank=True)
    passing_year = models.DateField(blank=True)
    degree_name = models.CharField(max_length=100, blank=True)
    department_name = models.CharField(max_length=100, blank=True)
    about = models.CharField(max_length=100, blank=True)
    image = models.CharField(max_length=100, blank=True)
    present_address = models.CharField(max_length=500, blank=True)
    permanent_address = models.CharField(max_length=500, blank=True)
    rating = models.FloatField(blank=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

posts/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout 

# Create your views here.

def homepage(request):
    return HttpResponse('homepage')

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.urls import reverse

def registerUser(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    else:
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('loginUser')
        form = CreateUserForm()
        return render(request, 'users/register.html', {'form': form})

def loginUser(request):
    print ('starts....')
    return redirect('posts:homepage')
    if request.user.is_authenticated:
        return redirect('posts:homepage')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username = username, password = password)
            if user is not None:
                login(request, user)
                print ('here.....')
                return redirect('posts:homepage')
            else:
                messages.info(request, 'Username or Password is incorrect')
        context = {}
        return render(request, 'users/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('posts:homepage')

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

   <title>
       {% block title %}
           Class Note Archive
       {% endblock %}
   </title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">


</head>
<body>

    {% block content %}

    {% endblock %}

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"> </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"> </script>

    {% block page_script %}

    {% endblock %}

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="/login/" method="post">
        {% csrf_token %}
        <label for="username">username: </label>
        <input id="username" type="text" name="username" value="{{ username }}">

        <label for="password">password: </label>
        <input id="password" type="password" name="password" value="{{ password }}">

        <input type="submit" value="SUBMIT">
        </form>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="{% url 'users:loginUser' %}" method="post">
        {% csrf_token %}
        <label for="username">username: </label>
        <input id="username" type="text" name="username" value="{{ username }}">

        <label for="password">password: </label>
        <input id="password" type="password" name="password" value="{{ password }}">

        <input type="submit" value="SUBMIT">
        </form>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="/register/" method="post">
        {% csrf_token %} 
        {{form}}
        <input type="submit" value="SUBMIT">
    </form>
</body>
</html>